.TH PULP_SCRIPT"1" "July 24" "" "User Commands"
.SH NAME
.B pull_script
\- A script that download configure and run application on pulpissimo on a fpga board.
.SH SYNOPSIS         
.B pulp_script
.SH DESCRIPTION          
.B pulp_script
is an interactive script with the main purpose of show how pulpissimo can be download and tested using \fB pulp_install\fR and \fBpulp_app\fR, inside the script there are the basic information about requirement and how use script, pulp_install and pulp_app  man pages will explain deeply operation performed and can be read in case of errors.
.PP                    
.SH OPTION
No option available
.SH SEE ALSO
.BR pulp_install() 1 
.BR pulp_app() 1 
.SH BUGS            
.SH CREDITS 
Created by Elia Ribaldone, Luca Fiore and Marcello Neri
